variables:
  GITHUB_USER: stegos
  GITHUB_REPO: stegos-external-libs

stages:
  - build
  - release
  - deploy

.build: &build_definition
  stage: build
  script:
    - ./build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - var/

build:linux:
  <<: *build_definition
  tags:
    - linux

build:macos:pbc:
  <<: *build_definition
  tags:
    - macos

release:
  stage: release
  tags:
    - linux
  only:
    - tags
  script:
    - github-release release --tag ${CI_COMMIT_TAG} -c ${CI_COMMIT_SHA} -d "${CI_COMMIT_MESSAGE}"

.deploy: &deploy_definition
  stage: deploy
  script:
    - ci/upload-file.sh $(cat var/local/artifact.txt)

deploy:linux:
  <<: *deploy_definition
  tags:
    - linux
  only:
    - tags
  dependencies:
    - build:linux

deploy:macos:
  <<: *deploy_definition
  tags:
    - linux
  only:
    - tags
  dependencies:
    - build:macos
